#! /bin/sh

sxhkd &
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 &
bash $HOME/git/dotfiles/scripts/startupmonitors &
numlockx on &
compton &
xsetroot -cursor_name left_ptr &
nitrogen --restore &

bspc monitor eDP-1 -s HDMI-1
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	 true
bspc config focused_border_color \#88c0d0
