#! /bin/sh

sxhkd &
numlockx on &
compton &

if [ -x ~/bin/dual_monitor_script ];then
      dual_monitor_script
fi

bash $HOME/.config/polybar/launch.sh & 
xsetroot -cursor_name left_ptr &
nitrogen --restore &
setxkbmap -option grp:alt_shift_toggle us,es &

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 10
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	 true
bspc config focused_border_color \#88c0d0

bspc rule -a spt desktop=^5
bspc rule -a firefox desktop=^2
bspc rule -a code desktop=^1
bspc rule -a Zathura state=tiled
