#! /bin/sh
## THIS GOES INTO BIN
internal_monitor=eDP
external_monitor=HDMI-A-0

monitor_add() {
	desktops=4 # How many desktops to move to the second monitor

	for desktop in $(bspc query -D -m $internal_monitor | sed "$desktops"q)
  do
		bspc desktop $desktop --to-monitor $external_monitor
  done

  # Remove "Desktop" created by bspwm
  bspc desktop Desktop --remove
}

monitor_remove() {
	bspc monitor $internal_monitor -a Desktop # Temp desktop because one desktop required per monitor

	# Move everything to external monitor to reorder desktops
	for desktop in $(bspc query -D -m $internal_monitor)
	do
		bspc desktop $desktop --to-monitor $external_monitor
	done

	# Now move everything back to internal monitor
	bspc monitor $external_monitor -a Desktop # Temp desktop

	for desktop in $(bspc query -D -m $external_monitor)
	do
		bspc desktop $desktop --to-monitor $internal_monitor
	done

	bspc desktop Desktop --remove # Remove temp desktops
}

if [[ $(xrandr -q | grep "$external_monitor connected") ]]; then
    xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 1366x768 --rotate normal --left-of eDP
    monitor_add
else
    xrandr --output eDP --primary --mode 1920x1080 --rotate normal
    monitor_remove
fi

bash $HOME/.config/polybar/launch.sh
